### ISSUE TITLE
Can't create aliases with special localhost destinations

### ISSUE THREAD

**Issue by madddi** [l-with/terraform-provider-mailcow#117]
First of all, thanks for your work, this provider has been incredibly useful for me.

## Bug description

Aliases wit special destinations like `null@localhost` or `spam@localhost` can't be created (anymore?). The documentation contains information about the special value `spam@localhost` for the `goto` parameter, so I'm assuming this did work in the past.

```
│ Error: resourceAliasCreate 'no-reply@example.com': danger (goto_invalid, null@localhost)
│
│   with mailcow_alias.this["no-reply@example.com"],
│   on main.tf line 45, in resource "mailcow_alias" "this":
│   45: resource "mailcow_alias" "this" {
```

Existing aliases also can't be modified to these values.

You can currently work around this issue by creating an alias with a different target, modifying it in the web UI and lastly adjusting the Terraform code.

**Comment by madddi** [comment]
You're right, it's the API. I did some digging and found out that there actually are special fields for discard/spam/ham:

```yaml
                goto_ham:
                  description: learn as ham
                  type: boolean
                goto_null:
                  description: silently ignore
                  type: boolean
                goto_spam:
                  description: learn as spam
                  type: boolean
```

As you'd expect, this payload works fine:

```json
{
  "active": "1",
  "address": "gh@example.com,
  "goto_spam": 1
}
```
